### ISSUE TITLE
Backend Setup

### ISSUE THREAD

**Issue by james0r** [wernerglinka/metalsmith-netlify-starter#1]
I followed the README and created an OAuth provider using Netlify Identity but i'm getting

```
Your Git Gateway backend is not returning valid settings. Please make sure it is enabled.
``` 
after logging in with Google auth. 

Followed some instructions to add `config.yml` with
```
backend:
  name: git-gateway
  repo: james0r/metalsmith-netlify-starter
  branch: main
```

But still getting the same error. What is needed to allow Netlify to see the backend?

Thanks.
